### ISSUE TITLE
Dockerfile should be open sourced as well

### ISSUE THREAD

**Issue by keyan** [jdumars/lekube#1]
Hi Jason, thanks for working on this great tool. I am currently evaluating it as part of a log management strategy, but I have some hesitations due to the fact that the [base image](https://hub.docker.com/r/jsingerdumars/lekube/) Dockerfile is not in this repo or otherwise accessible. I worry that if I need to make modifications or you discontinue support then I would be put in a difficult position.

Considering the above, can we copy the Dockerfile into this repo (or another)?

**Comment by keyan** [comment]
Hello @jdumars, wondering if you had a chance to look over this? I'm assuming you have no reservations with releasing the Dockerfile as you have already done so with SumoKube. Please let me know if there is any way to help out or expedite this. And thanks again for open-sourcing this :)

**Comment by jdumars** [comment]
Hey @keyan the Dockerfile and some other goodies are here:  https://github.com/rapid7/docker-logentries Let me know if you need anything else!

**Comment by keyan** [comment]
Oh I see, I assumed the Dockerfile was customized. Thanks Jason!
