### ISSUE TITLE
Can you please publish your Dockerfile?

### ISSUE THREAD

**Issue by dblackdblack** [jdumars/lekube#2]
I really love that you've put in the effort to make this a public project, but I can't really make use of it unless I know what's inside the docker image `jsingerdumars/lekube:latest` because security.

Can you please check in your Dockerfile?

**Comment by jdumars** [comment]
@dblackdblack sorry for the delay, you can find the Docker source information here:  https://github.com/rapid7/docker-logentries  I made an image to protect against breaking upstream changes.
